// frontend/src/routes/game/index.tsx
import { component$, useSignal, useTask$ } from '@builder.io/qwik';
import { routeLoader$, routeAction$, Form, useNavigate, type DocumentHead } from '@builder.io/qwik-city';
import { gameService } from '~/services/gameService';

/**
 * Loader pour l'état du jeu
 */
export const useGameState = routeLoader$(async ({ cookie, redirect }) => {
  const sessionId = cookie.get('session_id')?.value;
  const gameId = cookie.get('game_id')?.value;

  if (sessionId && gameId) {
    try {
      const gameState = await gameService.getGameState(sessionId, gameId);
      if (gameState) {
        throw redirect(302, '/game/read');
      }
    } catch (error) {
      if (!(error instanceof Error && error.message.includes('302'))) {
        cookie.delete('session_id', { path: '/' });
        cookie.delete('game_id', { path: '/' });
      }
    }
  }

  return { initialized: false };
});

/**
 * Action d'initialisation du jeu
 */
export const useInitGame = routeAction$(async (_, { cookie, redirect }) => {
  try {
    const gameState = await gameService.getGameState();
    if (!gameState?.sessionId || !gameState?.gameId) {
      return { success: false };
    }

    cookie.set('session_id', gameState.sessionId, { path: '/' });
    cookie.set('game_id', gameState.gameId, { path: '/' });
    
    throw redirect(302, '/game/read');
  } catch (error) {
    if (error instanceof Error && error.message.includes('302')) {
      throw error;
    }
    return { success: false };
  }
});

export default component$(() => {
  const state = useGameState();
  const initGame = useInitGame();
  const errorSignal = useSignal<string | null>(null);

  useTask$(({ track }) => {
    track(() => initGame.value?.success);
    
    if (initGame.value?.success === false) {
      errorSignal.value = 'Une erreur est survenue lors de l\'initialisation du jeu';
    } else {
      errorSignal.value = null;
    }
  });

  return (
    <div class="min-h-screen bg-gradient-to-b from-gray-900 to-gray-800 text-white">
      <div class="container mx-auto px-4 py-16">
        <div class="max-w-3xl mx-auto">
          {/* En-tête */}
          <div class="text-center mb-16">
            <h1 class="text-5xl font-bold mb-6 bg-clip-text text-transparent bg-gradient-to-r from-purple-400 to-pink-600">
              CASYS RPG
            </h1>
            <p class="text-xl text-gray-300">
              Plongez dans une aventure interactive unique
            </p>
          </div>

          {/* Formulaire ou Message de Redirection */}
          <div class="bg-gray-800 rounded-lg shadow-2xl p-8 border border-gray-700">
            <Form action={initGame}>
              <div class="space-y-6">
                <div class="text-center">
                  <h2 class="text-2xl font-semibold mb-4">Commencer l'Aventure</h2>
                  <p class="text-gray-400 mb-8">
                    Êtes-vous prêt à entrer dans un monde de mystères et de défis ?
                  </p>
                </div>

                <div class="flex justify-center">
                  <button
                    type="submit"
                    class="px-8 py-4 bg-gradient-to-r from-purple-600 to-pink-600 rounded-lg
                           font-semibold text-lg shadow-lg transform transition
                           hover:scale-105 hover:shadow-xl
                           focus:outline-none focus:ring-2 focus:ring-purple-500 focus:ring-opacity-50"
                  >
                    Débuter l'Histoire
                  </button>
                </div>

                {errorSignal.value && (
                  <div class="mt-4 text-center text-red-400">
                    {errorSignal.value}
                  </div>
                )}
              </div>
            </Form>
          </div>

          {/* Footer */}
          <div class="mt-12 text-center text-sm text-gray-500">
            <p>
              CASYS RPG 2024 - Un jeu de rôle interactif propulsé par l'IA
            </p>
          </div>
        </div>
      </div>
    </div>
  );
});

export const head: DocumentHead = {
  title: 'CASYS RPG',
  meta: [
    {
      name: 'description',
      content: 'Plongez dans une aventure interactive unique'
    }
  ]
};

// frontend/src/routes/game/+page.svelte
<script lang="ts">
  import { enhance } from '$app/forms';
  import { gameService } from '$lib/services/gameService';
  import type { PageData } from './$types';

  export let data: PageData;

  let loading = false;
  let error: string | null = null;

  async function handleSubmit() {
    loading = true;
    error = null;

    try {
      const response = await gameService.initialize();
      if (!response.success) {
        throw new Error(response.message || 'Failed to initialize game');
      }
    } catch (e) {
      console.error('Game initialization error:', e);
      error = e instanceof Error ? e.message : 'Une erreur est survenue lors de l\'initialisation du jeu';
    } finally {
      loading = false;
    }
  }
</script>

<div class="min-h-screen bg-game-background">
  <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-12">
    <div class="text-center">
      <!-- Hero Section -->
      <div class="animate-fade-in space-y-8 py-20">
        <div class="animate-float">
          <h1 class="text-6xl font-serif font-extrabold text-game-primary tracking-tight">
            CASYS RPG
          </h1>
          <p class="mx-auto mt-3 max-w-md text-xl text-game-secondary font-serif">
            Prêt pour l'aventure ?
          </p>
        </div>

        {#if error}
          <div class="mx-auto max-w-md">
            <div class="rounded-2xl bg-game-error/5 p-6 shadow-neu-flat animate-slide-in">
              <p class="text-game-error font-serif">{error}</p>
            </div>
          </div>
        {/if}

        <!-- CTA Button -->
        <div class="mt-16">
          <form 
            method="POST" 
            action="?/init"
            use:enhance={() => {
              return async ({ result }) => {
                if (result.type === 'redirect') {
                  window.location.href = result.location;
                }
              };
            }}
          >
            <button
              type="submit"
              disabled={loading}
              class="transform rounded-2xl bg-game-background px-12 py-6 text-xl font-serif font-semibold text-game-primary shadow-neu-flat hover:bg-opacity-95 active:shadow-neu-pressed transition-all duration-300 focus:outline-none disabled:opacity-50 flex mx-auto items-center space-x-3"
            >
              {#if loading}
                <svg class="h-6 w-6 animate-pulse-slow" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                  <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="1.5"></circle>
                  <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                </svg>
              {:else}
                <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M14.752 11.168l-3.197-2.132A1 1 0 0010 9.87v4.263a1 1 0 001.555.832l3.197-2.132a1 1 0 000-1.664z" />
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
              {/if}
              <span>{loading ? 'Initialisation...' : 'Commencer l\'aventure'}</span>
            </button>
          </form>
        </div>
      </div>

    </div>
  </div>

  <!-- Footer -->
  <footer class="py-8 mt-20">
    <div class="text-center text-game-secondary font-serif">
      <p> 2024 CASYS RPG - Une expérience narrative unique</p>
    </div>
  </footer>
</div>
